### ISSUE TITLE
Can't install on L11?

### ISSUE THREAD

**Issue by renege** [spatie/pest-plugin-route-testing#8]
Hi,

Why can't it install? It's an almost brand new L11 project.

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - spatie/pest-plugin-route-testing[0.0.3, ..., 0.0.5, 1.0.0] require pestphp/pest ^2.34.9 -> satisfiable by pestphp/pest[v2.34.9].
>     - spatie/pest-plugin-route-testing[0.0.1, ..., 0.0.2] require pestphp/pest ^2.5 -> satisfiable by pestphp/pest[v2.5.0, ..., v2.34.9].
>     - pestphp/pest[v2.34.7, ..., v2.34.9] require phpunit/phpunit ^10.5.17 -> satisfiable by phpunit/phpunit[10.5.17, ..., 10.5.29].
>     - pestphp/pest v2.34.6 requires phpunit/phpunit ^10.5.16 -> satisfiable by phpunit/phpunit[10.5.16, ..., 10.5.29].
>     - pestphp/pest v2.34.5 requires phpunit/phpunit ^10.5.15 -> satisfiable by phpunit/phpunit[10.5.15, ..., 10.5.29].
>     - pestphp/pest[v2.34.3, ..., v2.34.4] require phpunit/phpunit ^10.5.13 -> satisfiable by phpunit/phpunit[10.5.13, ..., 10.5.29].
>     - pestphp/pest v2.34.2 requires phpunit/phpunit ^10.5.12 -> satisfiable by phpunit/phpunit[10.5.12, ..., 10.5.29].
>     - pestphp/pest v2.34.1 requires phpunit/phpunit ^10.5.11 -> satisfiable by phpunit/phpunit[10.5.11, ..., 10.5.29].
>     - pestphp/pest[v2.33.5, ..., v2.34.0] require phpunit/phpunit ^10.5.10 -> satisfiable by phpunit/phpunit[10.5.10, ..., 10.5.29].
>     - pestphp/pest[v2.32.1, ..., v2.33.4] require phpunit/phpunit ^10.5.9 -> satisfiable by phpunit/phpunit[10.5.9, ..., 10.5.29].
>     - pestphp/pest v2.32.0 requires phpunit/phpunit ^10.5.7 -> satisfiable by phpunit/phpunit[10.5.7, ..., 10.5.29].
>     - pestphp/pest[v2.29.1, ..., v2.31.0] require phpunit/phpunit ^10.5.5 -> satisfiable by phpunit/phpunit[10.5.5, ..., 10.5.29].
>     - pestphp/pest[v2.28.1, ..., v2.29.0] require phpunit/phpunit ^10.5.3 -> satisfiable by phpunit/phpunit[10.5.3, ..., 10.5.29].
>     - pestphp/pest v2.28.0 requires phpunit/phpunit ^10.5.2 -> satisfiable by phpunit/phpunit[10.5.2, ..., 10.5.29].
>     - pestphp/pest v2.27.0 requires phpunit/phpunit ^10.5.1 -> satisfiable by phpunit/phpunit[10.5.1, ..., 10.5.29].
>     - pestphp/pest[v2.24.1, ..., v2.26.0] require phpunit/phpunit ^10.4.2 -> satisfiable by phpunit/phpunit[10.4.2, ..., 10.5.29].
>     - pestphp/pest[v2.23.1, ..., v2.24.0] require phpunit/phpunit ^10.4.1 -> satisfiable by phpunit/phpunit[10.4.1, ..., 10.5.29].
>     - pestphp/pest v2.23.0 requires phpunit/phpunit ^10.4.0 -> satisfiable by phpunit/phpunit[10.4.0, ..., 10.5.29].
>     - phpunit/phpunit[10.5.27, ..., 10.5.29] require sebastian/environment ^6.1.0 -> satisfiable by sebastian/environment[6.1.0].
>     - phpunit/phpunit[10.4.0, ..., 10.5.26] require sebastian/environment ^6.0 -> satisfiable by sebastian/environment[6.0.0, 6.0.1, 6.1.0].
>     - You can only install one version of a package, so only one of these can be installed: sebastian/environment[6.0.0, 6.0.1, 6.1.0, 7.0.0, 7.1.0, 7.2.0].
>     - brianium/paratest v7.5.0 requires sebastian/environment ^7.1.0 -> satisfiable by sebastian/environment[7.1.0, 7.2.0].
>     - pestphp/pest v2.5.0 requires nunomaduro/collision ^7.4.0 -> found nunomaduro/collision[v7.4.0, ..., v7.10.0] but it conflicts with your root composer.json require (^8.0).
>     - pestphp/pest[v2.5.1, ..., v2.5.2] require nunomaduro/collision ^7.5.0 -> found nunomaduro/collision[v7.5.0, ..., v7.10.0] but it conflicts with your root composer.json require (^8.0).
>     - pestphp/pest[v2.5.3, ..., v2.6.3] require nunomaduro/collision ^7.5.2 -> found nunomaduro/collision[v7.5.2, ..., v7.10.0] but it conflicts with your root composer.json require (^8.0).
>     - pestphp/pest[v2.7.0, ..., v2.8.1] require nunomaduro/collision ^7.6.0 -> found nunomaduro/collision[v7.6.0, ..., v7.10.0] but it conflicts with your root composer.json require (^8.0).
>     - pestphp/pest[v2.8.2, ..., v2.12.0] require nunomaduro/collision ^7.7.0 -> found nunomaduro/collision[v7.7.0, ..., v7.10.0] but it conflicts with your root composer.json require (^8.0).
>     - pestphp/pest v2.12.1 requires nunomaduro/collision ^7.8.0 -> found nunomaduro/collision[v7.8.0, v7.8.1, v7.9.0, v7.10.0] but it conflicts with your root composer.json require (^8.0).
>     - pestphp/pest[v2.12.2, ..., v2.19.1] require nunomaduro/collision ^7.8.1 -> found nunomaduro/collision[v7.8.1, v7.9.0, v7.10.0] but it conflicts with your root composer.json require (^8.0).
>     - pestphp/pest[v2.19.2, ..., v2.22.1] require nunomaduro/collision ^7.9.0 -> found nunomaduro/collision[v7.9.0, v7.10.0] but it conflicts with your root composer.json require (^8.0).
>     - Root composer.json requires brianium/paratest ^7.5 -> satisfiable by brianium/paratest[v7.5.0].
>     - Root composer.json requires spatie/pest-plugin-route-testing * -> satisfiable by spatie/pest-plugin-route-testing[0.0.1, ..., 0.0.5, 1.0.0].
> 
> You can also try re-running composer require with an explicit version constraint, e.g. "composer require spatie/pest-plugin-route-testing:*" to figure out if any version is installable, or "composer require spatie/pest-plugin-route-testing:^2.1" if you know which you need.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.

 ```
 "require": {
        "laravel/framework": "^11.9",
        "laravel/pulse": "^1.2",
        "laravel/tinker": "^2.9",
        "laravel/vapor-cli": "^1.65",
        "laravel/vapor-core": "^2.37",
        "nesbot/carbon": "*",
        "php": "^8.2"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "*",
        "brianium/paratest": "^7.5",
        "driftingly/rector-laravel": "*",
        "fakerphp/faker": "^1.23",
        "itsgoingd/clockwork": "^5.2",
        "jasonmccreary/laravel-test-assertions": "^2.4",
        "larastan/larastan": "^2.9",
        "laravel-shift/blueprint": "^2.10",
        "laravel/pint": "^1.17",
        "laravel/sail": "^1.26",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.0",
        "phpunit/phpunit": "^11.0.1",
        "rector/rector": "*",
        "shipmonk/composer-dependency-analyser": "*",
        "spatie/laravel-error-solutions": "^1.0",
        "spatie/laravel-ray": "*"
    },
```

**Comment by ludoguenet** [comment]
Hey, just also got a brand new L11 app and it seems to work well. My dependencies:

```json
    "require": {
        "php": "^8.2",
        "laravel/framework": "^11.9",
        "laravel/tinker": "^2.9"
    },
    "require-dev": {
        "fakerphp/faker": "^1.23",
        "laravel/pint": "^1.13",
        "laravel/sail": "^1.26",
        "mockery/mockery": "^1.6",
        "nunomaduro/collision": "^8.0",
        "pestphp/pest": "^2.34",
        "pestphp/pest-plugin-laravel": "^2.4",
        "spatie/pest-plugin-route-testing": "^1.0"
    },
```

**Comment by pb30** [comment]
@renege Pest requires PHPUnit 10.x, your composer has 11.x. Remove PHPUnit and add install Pest first.
